const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const base=process.argv[2]||'http://127.0.0.1:8080';
(async()=>{
 const d=await(await fetch(base+'/api/demo/trace')).json();
 assert.equal(d.ratings.length,150);assert.equal(d.users.length,15);assert.equal(d.movies.length,15);
 assert.equal(d.matrix.flatMap(r=>r.values).filter(x=>x==null).length,75);
 assert.deepEqual(d.neighbors.map(x=>x.user),['Bình','Dũng']);
 for(const s of d.similarities){const a=d.matrix.find(x=>x.userId===1),b=d.matrix.find(x=>x.userId===s.userId);const pairs=a.values.map((x,i)=>[x,b.values[i]]).filter(x=>x.every(v=>v!=null));const means=[0,1].map(i=>pairs.reduce((t,x)=>t+x[i],0)/pairs.length);let num=0,aa=0,bb=0;for(const [x,y]of pairs){num+=(x-means[0])*(y-means[1]);aa+=(x-means[0])**2;bb+=(y-means[1])**2;}const result=num/Math.sqrt(aa*bb);if(Number.isFinite(result))assert.ok(Math.abs(result-s.value)<1e-5);else assert.equal(s.value,null);}
 for(const c of d.candidates){assert.ok(Math.abs(c.contributions.reduce((t,x)=>t+x.similarity*x.rating,0)-c.numerator)<1e-5);if(c.contributions.length>1)assert.ok(Math.abs(c.numerator/c.denominator-c.prediction)<1e-5);else assert.equal(c.prediction,null);}
 assert.equal(d.topN[0].movie,'Interstellar');
 const csv=await(await fetch(base+'/api/dataset')).text();
 const upload=async(body)=>fetch(base+'/api/dataset',{method:'POST',body,headers:{'Content-Type':'text/csv'}});
 const modified=csv.replace(/^(2,Bình,7,Interstellar,)5$/m,'$11').replace(/^(3,Dũng,7,Interstellar,)5$/m,'$11');
 const changed=await(await upload(modified)).json();assert.notEqual(changed.topN[0].movie,'Interstellar');
 const bad=await upload(csv+'\n'+csv.split(/\r?\n/)[1]);assert.equal(bad.status,400);
 assert.equal((await upload(csv.replace(',5\n',',6\n'))).status,400);
 const {parseHTML}=require('./.tools/dom-test/node_modules/linkedom');
 const {document}=parseHTML(fs.readFileSync('src/main/resources/web/index.html','utf8'));
 const node=s=>document.querySelector(s);
 const context=vm.createContext({document,fetch:(url,opts)=>fetch(base+url,opts),setTimeout,clearTimeout,performance:{now:()=>0},requestAnimationFrame:()=>1,cancelAnimationFrame(){},console});
 // Window.top is an unforgeable property: declaring a global function top fails in browsers.
 Object.defineProperty(context,'top',{get:()=>context,configurable:false});
 const servedScript=await(await fetch(base+'/app.js')).text();
 assert.equal(servedScript.replace(/\r\n/g,'\n').trim(),fs.readFileSync('src/main/resources/web/app.js','utf8').replace(/\r\n/g,'\n').trim(),'Server must serve the latest build');
 vm.runInContext(servedScript,context);
 for(let i=0;i<100&&!vm.runInContext('state.ready',context);i++)await new Promise(r=>setTimeout(r,10));
 assert.ok(vm.runInContext('state.ready',context));
 for(let step=0;step<7;step++)for(const progress of[0,.25,.7,1]){vm.runInContext(`state.step=${step};state.elapsed=state.duration*${progress};render()`,context);assert.ok(!/undefined|NaN/.test(node('#visual').innerHTML),`step ${step}, ${progress}`);}
 vm.runInContext('go(1)',context);assert.equal((node('#visual').innerHTML.match(/class="missing/g)||[]).length,75);
 vm.runInContext('replay();playPause()',context);assert.equal(vm.runInContext('state.playing',context),false);
 vm.runInContext('go(2)',context);assert.ok(node('#visual').innerHTML.includes('Bình'));
 node('#intro-start').onclick();
 assert.equal(vm.runInContext('state.playing',context),true);
 assert.ok(node('#intro').classList.contains('hidden'),'Start hides the intro');
 vm.runInContext('tick(6000)',context);
 assert.ok(node('#visual').innerHTML.includes('Đọc 75 / 150'),'Start advances visible CSV animation');
 node('#play').onclick();assert.equal(vm.runInContext('state.playing',context),false);
 const paused=node('#visual').innerHTML;vm.runInContext('tick(9000)',context);assert.equal(node('#visual').innerHTML,paused);
 node('#play').onclick();assert.equal(vm.runInContext('state.playing',context),true);
 node('#intro-start').onclick();
 for(let i=1;i<=7;i++)vm.runInContext(`tick(${i*12000})`,context);
 assert.equal(vm.runInContext('state.step',context),6);assert.equal(vm.runInContext('state.playing',context),false);
 assert.ok(node('#visual').innerHTML.includes('Interstellar'));
 node('#overview').onclick();assert.ok(!node('#intro').classList.contains('hidden'));
 node('#manual-start').onclick();assert.ok(node('#intro').classList.contains('hidden'));assert.equal(vm.runInContext('state.playing',context),false);
 vm.runInContext('go(1);state.elapsed=state.duration*.2;visual()',context);
 const scroller=node('.matrix-scroll'),cell=node('[data-cell="1/1"]');
 scroller.scrollTop=130;scroller.scrollLeft=60;
 const stage=node('#visual');let writes=0;
 let htmlOwner=Object.getPrototypeOf(stage);while(!Object.getOwnPropertyDescriptor(htmlOwner,'innerHTML'))htmlOwner=Object.getPrototypeOf(htmlOwner);
 const htmlProperty=Object.getOwnPropertyDescriptor(htmlOwner,'innerHTML');
 Object.defineProperty(stage,'innerHTML',{configurable:true,get(){return htmlProperty.get.call(this);},set(v){writes++;htmlProperty.set.call(this,v);}});
 for(let i=31;i<=150;i++)vm.runInContext(`state.elapsed=state.duration*${i}/150;visual()`,context);
 assert.equal(node('.matrix-scroll'),scroller,'Matrix container must not be replaced');
 assert.equal(node('[data-cell="1/1"]'),cell,'Matrix cells must not be replaced');
 assert.equal(scroller.scrollTop,130);assert.equal(scroller.scrollLeft,60);assert.equal(writes,0);
 assert.equal(node('#visual').querySelectorAll('td.missing').length,75);
 vm.runInContext('go(6);state.elapsed=0;visual()',context);
 const cards=[...document.querySelectorAll('.rank-card')];assert.equal(cards.length,2);
 writes=0;
 vm.runInContext('state.elapsed=state.duration*.4;visual()',context);
 assert.equal(document.querySelectorAll('.rank-card.pending').length,1);
 for(let i=61;i<=150;i++)vm.runInContext(`state.elapsed=state.duration*${i}/150;visual()`,context);
 assert.equal(document.querySelectorAll('.rank-card.pending').length,0);
 assert.equal(document.querySelectorAll('.rank-card')[0],cards[0]);assert.equal(document.querySelectorAll('.rank-card')[1],cards[1]);
 assert.equal(writes,0,'Top-2 must not recreate DOM or restart entry effects');
 console.log('PASS: stable matrix nodes, scroll coordinates retained, stable Top-2 slots, no per-frame HTML replacement; browser top collision regression, latest served build, start click, visible animation, pause/resume, full seven-step playback, manual controls, dataset and Mahout calculations.');
})().catch(e=>{console.error(e);process.exitCode=1;});
